#!/usr/bin/env python3
"""Generate bounce_sounds.h with PCM sound effects for Pogn."""

import math
import struct

SAMPLE_RATE = 44100

def generate_tone(freq, duration_ms, volume=0.8):
    """Generate a tone with ADSR envelope."""
    num_samples = int(SAMPLE_RATE * duration_ms / 1000)
    samples = []

    attack = int(num_samples * 0.05)
    decay = int(num_samples * 0.1)
    release = int(num_samples * 0.3)
    sustain_level = 0.6

    for i in range(num_samples):
        # Envelope
        if i < attack:
            env = i / attack
        elif i < attack + decay:
            env = 1.0 - (1.0 - sustain_level) * (i - attack) / decay
        elif i < num_samples - release:
            env = sustain_level
        else:
            env = sustain_level * (num_samples - i) / release

        sample = math.sin(2 * math.pi * freq * i / SAMPLE_RATE) * env * volume
        samples.append(int(max(-32767, min(32767, sample * 32767))))

    return samples

def write_header(filename, sounds):
    """Write sounds as C header file."""
    with open(filename, 'w') as f:
        f.write("// Auto-generated by generate_sounds.py\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")

        names = []
        for name, samples in sounds:
            names.append(name)
            f.write(f"static const int16_t {name}[] = {{\n")
            for i in range(0, len(samples), 16):
                chunk = samples[i:i+16]
                f.write("    " + ", ".join(str(s) for s in chunk) + ",\n")
            f.write("};\n")
            f.write(f"static const uint32_t {name}_length = {len(samples)};\n\n")

        # Lookup arrays
        f.write(f"#define NUM_SOUNDS {len(sounds)}\n\n")
        f.write("enum {\n")
        for i, name in enumerate(names):
            f.write(f"    SOUND_{name.upper().replace('SOUND_', '')} = {i},\n")
        f.write("};\n\n")
        f.write("static const int16_t* bounce_samples[] = {\n")
        for name in names:
            f.write(f"    {name},\n")
        f.write("};\n\n")
        f.write("static const uint32_t bounce_lengths[] = {\n")
        for name in names:
            f.write(f"    {name}_length,\n")
        f.write("};\n")

if __name__ == "__main__":
    sounds = [
        ("sound_paddle_hit", generate_tone(440, 100, 0.8)),
        ("sound_wall_bounce", generate_tone(330, 80, 0.6)),
        ("sound_score", generate_tone(220, 200, 0.7)),
    ]
    write_header("main/bounce_sounds.h", sounds)
    print(f"Generated main/bounce_sounds.h with {len(sounds)} sounds")
